# Generated by Django 4.2 on 2023-04-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_is_admin_customuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('stud', 'student'), ('teach', 'teacher'), ('parent', 'parent'), ('oth', 'other')], max_length=6, null=True, verbose_name='user_type'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['-created_at'], name='users_created_30b417_idx'),
        ),
    ]
