version: '3.9'

services:

  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "8080:5432"
    environment:
      POSTGRES_USER: maxim
      POSTGRES_PASSWORD: 0912
      POSTGRES_DB: teacher
