version: '3.9'

services:

  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "8080:5432"
    environment:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
